### ISSUE TITLE
Re-ordering Duplicates new entries

### ISSUE THREAD

**Issue by timetravelopps** [timetravelopps/wireframer#1] opened 2015-11-06 14:43 UTC
When I add a page element to the list, and then re-order the list, and then save the re-ordered list, the new page element is duplicated.

**Comment by timetravelopps** [comment] 2015-11-06 15:31
(this was a bug in the initial brief)

**Comment by g105b** [comment] 2015-11-09 12:28
Open the Chrome Web Developer panel, and look at the Network tab.

When we create a new entry, you can see this done by posting the data to create.php:
![wf1](https://cloud.githubusercontent.com/assets/358014/11033457/2bec7baa-86db-11e5-8cba-99ae0ab71c21.png)

Next, when we reorder the elements, there are two requests made; the posted data to order_update.php, and the refreshed page:
![wf2](https://cloud.githubusercontent.com/assets/358014/11033470/4f724190-86db-11e5-8eed-26cf74afbfda.png)
![wf3](https://cloud.githubusercontent.com/assets/358014/11033474/52c48f42-86db-11e5-841e-b7962a4a5611.png)

The problem is that when the page is refreshed, any existing post data is sent along with the request again, so our app can preserve its state - but actually our app is using the post data to manipulate the database. In turn, the app reacts to the post data for a second time... not intended.

A simple fix is shown in commit f057efe0dbb8a0c1670a41a41cff7242ec2c3d7b which I have just done on its own branch.

Thanks to Github's excellent issue tracker, as soon as you're happy that this fixes the issue and merge my change into master, it will automatically close this issue. This is because I put `fixes #1` in the commit message.

**Closed as completed** 2015-11-09 13:31 UTC

**Comment by g105b** [comment] 2015-11-10 09:36
In reply to https://github.com/timetravelopps/wireframer/commit/f057efe0dbb8a0c1670a41a41cff7242ec2c3d7b#commitcomment-14288337

I would recommend two methods of setting up a server in this context:
1. Use rewrite rules so that the server and the application that is being served behaves as if it was as the root directory of the domain. The path `/` should really get you to the top of the current application you're in.
2. Use a subdomain to distinguish different projects on the same server -- then each project will be working from the root path. `myproject.timetravelopps.co.uk/` rather than `timetravelopps.co.uk/myproject/`
